name: Deploy to heroku

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # For example, if you have a Dockerfile in the root of your project, leave it as follows:
          dockerfile_directory: ./
          # (Optional, default: "Dockerfile")
          # Dockerfile name.
          dockerfile_name: Dockerfile
          # (Optional, default: "")
          # Additional options of docker build command.
          #docker_options: "--no-cache"
          
          # (Optional, default: "web")
          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          # For more information look at https://devcenter.heroku.com/articles/process-model
          process_type: web
